services:
  wordpress:
    build: .
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX}
      WORDPRESS_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG' , '/var/www/log/wp-errors.log' );
        define ( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 0 );
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    volumes:
      - ./html:/var/www/html
      - ./log:/var/www/log
    depends_on:
      - db
  db:
    image: mysql:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306

networks:
  default:
    name: localhost-network
    external: true
