services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG' , '/var/www/log/wp-errors.log' );
        define ( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 0 );
      FULL_LOCAL_PATH: ${FULL_LOCAL_PATH} # For use in ray.php
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    volumes:
      - ./html:/var/www/html
      - ./log:/var/www/log
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./ray.php:/var/www/ray.php
    depends_on:
      - db
  db:
    image: mysql:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_UNIQUE_PORT}:3306

networks:
  default:
    name: localhost-network
    external: true
